/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface CheckRunData {
	owner?: string;
	repo: string;
	head_sha?: string;
	details_url?: string;
	status?: 'created' | 'queued' | 'in_progress' | 'completed';
	started_at?: string;
	conclusion?:
		| (
				| 'action_required'
				| 'cancelled'
				| 'failure'
				| 'neutral'
				| 'success'
				| 'skipped'
				| 'stale'
				| 'timed_out'
		  )
		| null;
	completed_at?: string | null;
	check_run_id?: number;
	output?: {
		actions?: {
			label?: string;
			identifier?: string;
			description?: string;
			[k: string]: unknown;
		}[];
		[k: string]: unknown;
	};
	check_suite?: {
		id?: number;
		pull_requests?: string[];
		[k: string]: unknown;
	};
	participants?: unknown[];
	mentionsUser?: unknown[];
	alertsUser?: unknown[];
	mentionsGroup?: unknown[];
	alertsGroup?: unknown[];
	[k: string]: unknown;
}

export interface CheckRunContractDefinition
	extends ContractDefinition<CheckRunData> {}

export interface CheckRunContract extends Contract<CheckRunData> {}
