/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface CommitData {
	org: string;
	repo: string;
	head: {
		sha: string;
		branch: string;
		[k: string]: unknown;
	};
	$transformer?: {
		/**
		 * all downstream contracts are mergeable
		 */
		mergeable?: boolean & string;
		/**
		 * PR is merged
		 */
		merged?: boolean;
		[k: string]: unknown;
	};
	participants?: unknown[];
	mentionsUser?: unknown[];
	alertsUser?: unknown[];
	mentionsGroup?: unknown[];
	alertsGroup?: unknown[];
	[k: string]: unknown;
}

export interface CommitContractDefinition
	extends ContractDefinition<CommitData> {}

export interface CommitContract extends Contract<CommitData> {}
