/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface GhPushData {
	before: string;
	after: string;
	commits?: {
		[k: string]: unknown;
	}[];
	author?: string;
	branch: string;
	[k: string]: unknown;
}

export interface GhPushContractDefinition
	extends ContractDefinition<GhPushData> {}

export interface GhPushContract extends Contract<GhPushData> {}
