/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

export type {
	GithubOrgContract,
	GithubOrgContractDefinition,
	GithubOrgData,
} from './github-org';
export type {
	IssueContract,
	IssueContractDefinition,
	IssueData,
} from './issue';
export type {
	PullRequestContract,
	PullRequestContractDefinition,
	PullRequestData,
} from './pull-request';
export type {
	RepositoryContract,
	RepositoryContractDefinition,
	RepositoryData,
} from './repository';
