/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export type Status = 'open' | 'closed';

export interface IssueData {
	repository: string;
	mirrors?: string[];
	description?: string;
	status?: Status;
	archived?: boolean;
	participants?: unknown[];
	mentionsUser?: unknown[];
	alertsUser?: unknown[];
	mentionsGroup?: unknown[];
	alertsGroup?: unknown[];
	[k: string]: unknown;
}

export interface IssueContractDefinition
	extends ContractDefinition<IssueData> {}

export interface IssueContract extends Contract<IssueData> {}
