/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from 'autumndb';

export interface PullRequestData {
	description?: string;
	status?: 'open' | 'closed';
	archived?: boolean;
	head?: {
		branch: string;
		sha: string;
		[k: string]: unknown;
	};
	base?: {
		branch: string;
		sha: string;
		[k: string]: unknown;
	};
	created_at?: string | null;
	merged_at?: string | null;
	repository?: string;
	mirrors?: string[];
	participants?: unknown[];
	mentionsUser?: unknown[];
	alertsUser?: unknown[];
	mentionsGroup?: unknown[];
	alertsGroup?: unknown[];
	[k: string]: unknown;
}

export interface PullRequestContractDefinition
	extends ContractDefinition<PullRequestData> {}

export interface PullRequestContract extends Contract<PullRequestData> {}
