version: '2.1'

services:
  sut:
    image: balena/jellyfish-sut:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - LOGLEVEL=error
    secrets:
      - integration_github_app_id
      - integration_github_private_key
      - integration_github_signature_key
      - integration_github_token
    networks:
      - internal

secrets:
  integration_github_app_id:
    file: ./.balena/secrets/integration_github_app_id
  integration_github_private_key:
    file: ./.balena/secrets/integration_github_private_key
  integration_github_signature_key:
    file: ./.balena/secrets/integration_github_signature_key
  integration_github_token:
    file: ./.balena/secrets/integration_github_token
