/*
 * Copyright (C) Balena.io - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 *
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type
import { core } from '@balena/jellyfish-types';
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CheckRunData {
	owner?: string;
	repo: string;
	head_sha?: string;
	details_url?: string;
	status?: 'created' | 'queued' | 'in_progress' | 'completed';
	started_at?: string;
	conclusion?:
		| (
				| 'action_required'
				| 'cancelled'
				| 'failure'
				| 'neutral'
				| 'success'
				| 'skipped'
				| 'stale'
				| 'timed_out'
		  )
		| null;
	completed_at?: string | null;
	check_run_id?: number;
	output?: {
		actions?: {
			label?: string;
			identifier?: string;
			description?: string;
			[k: string]: unknown;
		}[];
		[k: string]: unknown;
	};
	check_suite?: {
		id?: number;
		pull_requests?: string[];
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface CheckRunContractDefinition
	extends core.ContractDefinition<CheckRunData> {}
export interface CheckRunContract extends core.Contract<CheckRunData> {}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CommitData {
	org: string;
	repo: string;
	head: {
		sha: string;
		branch: string;
		[k: string]: unknown;
	};
	$transformer?: {
		artifactReady?: boolean;
		/**
		 * all downstream contracts are mergeable
		 */
		mergeable?: boolean;
		/**
		 * PR is merged
		 */
		merged?: boolean;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface CommitContractDefinition
	extends core.ContractDefinition<CommitData> {}
export interface CommitContract extends core.Contract<CommitData> {}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GhPushData {
	before: string;
	after: string;
	commits?: {
		[k: string]: unknown;
	}[];
	author?: string;
	branch: string;
	[k: string]: unknown;
}

export interface GhPushContractDefinition
	extends core.ContractDefinition<GhPushData> {}
export interface GhPushContract extends core.Contract<GhPushData> {}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GithubOrgData {
	description?: string;
	[k: string]: unknown;
}

export interface GithubOrgContractDefinition
	extends core.ContractDefinition<GithubOrgData> {}
export interface GithubOrgContract extends core.Contract<GithubOrgData> {}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Status = 'open' | 'closed';

export interface IssueData {
	repository: string;
	mirrors?: string[];
	description?: string;
	status?: Status;
	archived?: boolean;
	[k: string]: unknown;
}

export interface IssueContractDefinition
	extends core.ContractDefinition<IssueData> {}
export interface IssueContract extends core.Contract<IssueData> {}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PullRequestData {
	description?: string;
	status?: 'open' | 'closed';
	archived?: boolean;
	head?: {
		branch: string;
		sha: string;
		[k: string]: unknown;
	};
	base?: {
		branch: string;
		sha: string;
		[k: string]: unknown;
	};
	created_at?: string | null;
	merged_at?: string | null;
	repository?: string;
	mirrors?: string[];
	[k: string]: unknown;
}

export interface PullRequestContractDefinition
	extends core.ContractDefinition<PullRequestData> {}
export interface PullRequestContract extends core.Contract<PullRequestData> {}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RepositoryData {
	owner?: string;
	name?: string;
	git_url?: string;
	html_url?: string;
	[k: string]: unknown;
}

export interface RepositoryContractDefinition
	extends core.ContractDefinition<RepositoryData> {}
export interface RepositoryContract extends core.Contract<RepositoryData> {}
